on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to approve PRs
    steps:
      - name: Autoapproval
        id: autapproval
        uses: dkhmelenko/autoapproval@v1.0
        with:
          who-to-greet: 'Mona the Octocat'
