on:
  pull_request:
    types: [opened, reopened]
    
permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write
  statuses: write
  
jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval
    steps:
      - uses: dkhmelenko/autoapproval@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
